apiVersion: v1
kind: Service
metadata:
  name: php-apache-svc
  namespace: app
spec:
  selector:
    app: php-apache
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
